### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by pleary**
Some changes to get Travis CI builds working again

### CODE REVIEW

**Comment by Taher-Ghaleb** [comment]
Hello,

Sorry, I know it's been a long time ago, but I am curious bundler caching was available since December 17, 2014, but I see you just enabled it in this pull request (which is in 2016). Any reasons, please? 

Thanks.

**Comment by kueda** [comment]
I don't recall, but I suspect we enabled it to speed up the build. FWIW, we use Github Actions for CI these days, not Travis.

**Comment by Taher-Ghaleb** [comment]
I see. But, what I meant, why wasn't enabled earlier? The caching feature was available one year earlier. Thanks for your response, @kueda.

**Comment by kueda** [comment]
Maybe b/c we didn't know about it? I doubt any of us remember, but in general we don't know about every feature of every piece of software we use, and we don't use every feature we know about.

**Comment by Taher-Ghaleb** [comment]
I got your point. Thanks again, @kueda. I appreciate your response.

**Pull request merged**
