### PR TITLE
added translations

### PR DESCRIPTION
**Pull request by schnautzr**
added translations for en.twitter, en.facebook

### CODE REVIEW

**Comment by kueda** [comment]
Hey @schnautzr, thanks for that, and thanks for using a pull request. Couple issues, though:

1. Are these translations being used anywhere? If not, is there a reason you're adding them? Maybe you forgot to add some of the changes to the files that use them?
1. We try to have translation keys correspond to their translations, so a better key for `Follow or tweet us!` would be `follow_or_tweet_us`.
1. There are numerous sites using our code, so we try to keep references to iNaturalist out of the translations. Things like `iNaturalist.org on Facebook` should be replaced with `%{site_name} on Facebook`

**Comment by schnautzr** [comment]
Hi...I'm new to this pull request stuff. I am attempting to address the issue where if you hover over the links at the bottom of the site that say "Facebook" and "Twitter" and see tooltips that complain about there not being translations for en.facebook and en.twitter.

Rob

----- Original Message -----

**Comment by kueda** [comment]
Got it. Ok, so those are used at https://github.com/inaturalist/inaturalist/blob/master/app/views/shared/_footer.html.haml#L8, but I think a better approach there would be to not translate them at all, since I don't think they use different names in different languages, right? Facebook is still "Facebook" no matter what language you speak? So to fix that you might replace `pieces << link_to(t(:facebook), site.facebook_url) unless site.facebook_url.blank?` with `pieces << link_to("facebook", site.facebook_url) unless site.facebook_url.blank?`. 

If I'm wrong and they *do* have different names in different languages, then you'd want to translate them as they are used in those languages, not as some other string like "Follow us on Facebook." So `facebook: Facebook` might go in `en.yml`, `facebook: フェイスブック` might go in `ja.yml`, etc.

**Comment by kueda** [comment]
I'm closing this since you haven't responded in 6 months. If you still want to do something like this, I'd recommend updating your fork, b/c there have been many translation changes since you opened this PR.

**Pull request closed without merging**
