### PR TITLE
Update debugger

### PR DESCRIPTION
**Pull request by strika**
Update `debugger` gem dependencies so it's possible to install gems locally. Old dependencies are yanked.

### CODE REVIEW

**Comment by kueda** [comment]
Hm, have you tried the Rails 4 branch? https://github.com/inaturalist/inaturalist/tree/rails4. I bet that resolves this. If that solves your problem I'll just close this.

**Comment by strika** [comment]
Yes - `rails4` branch installs gems cleanly. Is that the branch a potential contributor should start with?

**Comment by kueda** [comment]
Just merged Rails 4 into master. If this issue is now solved, can you close this pr?

**Comment by strika** [comment]
Gems install cleanly now. I closed the issue, but it was reopened.

**Pull request closed without merging**
