### PR TITLE
Escape $

### PR DESCRIPTION
**Pull request by albert-ziegler**
Hi,

This is a minor fix for an unescaped `$` in a regEx I noticed while browsing this project's site on [LGTM](https://lgtm.com/projects/g/inaturalist/inaturalist/alerts/?mode=list&severity=error) (I work for the company behind that website).

### CODE REVIEW

**Comment by kueda** [comment]
It's not an unesecaped `$`, it's a variable in a regex, so if `text` is `"foo (bar)"` and `status.status` is `"bar"`, `text.match( /\(${status.status}\)/ )` should match. The duplicate `dataType` seems legit, though, so if you can remove the `$` change I'll merge this.

**Comment by albert-ziegler** [comment]
:+1: Ah, of course, that makes sense.

I'm not sure it's possible to combine template strings and regex literals though ([example](https://www.w3schools.com/code/tryit.asp?filename=FZY6G2OE3J76)).

Maybe the best way out is to use the RegExp constructor? I've suggested that one.

**Comment by kueda** [comment]
I think you're right about the regexp literal. Oops. However, I think you want
```javascript
if ( !text.match( new RegExp( `(${status.status})` ) )
```
 to match a string like `(status)`, right? No need to escape parens in a normal template string.

**Comment by albert-ziegler** [comment]
Good point, there's no need to escape the brackets.

**Comment by kueda** [comment]
Cool, thanks!

**Pull request merged**
