### PR TITLE
Update lifelists as lists

### PR DESCRIPTION
**Pull request by loarie**
update life_lists as normal lists and remove observation stats from all lists except checklists

### CODE REVIEW

**Comment by loarie** [comment]
@kueda I think this is ready to go - defer to you on our merge/deploy timeline this week though

**Review by kueda — CHANGES_REQUESTED** [review]
Aside from the inline comments I think this mostly looks fine. IMO, the new life list page needs some kind of navigational element to get back to lists/:login, but I'm not sure that needs to block release.

**Comment by loarie** [comment]
@kueda - ok I moved refresh_now and add_from_observations_now back to lists_controller and at least those methods now work. Do you think that did the trick?

**Comment by kueda** [comment]
It's still broken for me. Is it for you? Try running "Refresh" or "Reload from observations" on a place check list page. The problems I noted above are not about restoring actions to the `ListsController`, but rather methods to the `List` model.

FWIW, I'm not sure why we're going to maintain that functionality at all if it's going to be admin-only. I don't think I've clicked either of those buttons in years.

**Comment by loarie** [comment]
its working for me locally:
`tools -> refresh`
```
Started POST "/lists/300/refresh_now" for ::1 at 2021-02-10 16:42:05 -0800
Processing by ListsController#refresh_now as JS
  Parameters: {"tries"=>"1", "authenticity_token"=>"XmJitCIVFVeAI7E5dBLi39dxfFVqginzmaXmTDSF9uXRJiACCanUWz82D5SbiW47fWiaT6JI5IjKX4Fmdespcg==", "id"=>"300"}
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 6]]
  Preference Load (0.8ms)  SELECT "preferences".* FROM "preferences" WHERE "preferences"."owner_type" = 'User' AND "preferences"."owner_id" IN (6)
  User: qwertyuiop 6
  Site Load (1.2ms)  SELECT  "sites".* FROM "sites" WHERE (url LIKE '%localhost%')  ORDER BY "sites"."id" ASC LIMIT 1
down_retry_delay not reached for localhost:11211 (29.611 seconds left)
  Site Load (1.1ms)  SELECT  "sites".* FROM "sites"  ORDER BY "sites"."id" ASC LIMIT 1
  Preference Load (0.8ms)  SELECT "preferences".* FROM "preferences" WHERE "preferences"."owner_type" = 'Site' AND "preferences"."owner_id" IN (1)
down_retry_delay not reached for localhost:11211 (29.605 seconds left)
down_retry_delay not reached for localhost:11211 (29.603 seconds left)
  Site Load (0.7ms)  SELECT  "sites".* FROM "sites" WHERE "sites"."id" = $1 LIMIT 1  [["id", 1]]
  Preference Load (0.4ms)  SELECT "preferences".* FROM "preferences" WHERE "preferences"."owner_id" = $1 AND "preferences"."owner_type" = $2 AND "preferences"."group_id" IS NULL AND "preferences"."group_type" IS NULL  [["owner_id", 1], ["owner_type", "Site"]]
  List Load (0.7ms)  SELECT  "lists".* FROM "lists" WHERE "lists"."id" = $1 LIMIT 1  [["id", 300]]
  CheckList Exists (1.0ms)  SELECT  1 AS one FROM "lists" INNER JOIN "flags" ON "flags"."flaggable_id" = "lists"."id" AND "flags"."flaggable_type" = $1 WHERE "lists"."type" IN ('CheckList') AND "flags"."flag" = $2 AND "flags"."resolved" = $3 AND "lists"."id" = $4 LIMIT 1  [["flaggable_type", "List"], ["flag", "spam"], ["resolved", "f"], ["id", 300]]
  Role Load (0.8ms)  SELECT DISTINCT "roles".* FROM "roles" INNER JOIN "roles_users" ON "roles"."id" = "roles_users"."role_id" WHERE "roles_users"."user_id" = $1  [["user_id", 6]]
down_retry_delay not reached for localhost:11211 (29.583 seconds left)
down_retry_delay not reached for localhost:11211 (29.582 seconds left)
  Rendered text template (0.0ms)
Finished POST /lists/300/refresh_now from ::1 for user: qwertyuiop 6
Completed 200 OK POST /lists/300/refresh_now in 50ms (Views: 0.6ms | ActiveRecord: 9.0ms | Elasticsearch: 0.0ms)
```
and 'tools -> reload from observations`
```
Started POST "/lists/300/add_from_observations_now" for ::1 at 2021-02-10 16:43:01 -0800
Processing by ListsController#add_from_observations_now as JS
  Parameters: {"tries"=>"1", "authenticity_token"=>"60xtyEO4v3j JdZz6P7Htxhd62BcfpDToW03cMsssaVkCC9 aAR dEEwaN4HZUtTskQNepS0Xajyl1BaikJuMg==", "id"=>"300"}
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 6]]
  Preference Load (0.7ms)  SELECT "preferences".* FROM "preferences" WHERE "preferences"."owner_type" = 'User' AND "preferences"."owner_id" IN (6)
  User: qwertyuiop 6
  Site Load (0.8ms)  SELECT  "sites".* FROM "sites" WHERE (url LIKE '%localhost%')  ORDER BY "sites"."id" ASC LIMIT 1
down_retry_delay not reached for localhost:11211 (54.817 seconds left)
  Site Load (1.0ms)  SELECT  "sites".* FROM "sites"  ORDER BY "sites"."id" ASC LIMIT 1
  Preference Load (0.6ms)  SELECT "preferences".* FROM "preferences" WHERE "preferences"."owner_type" = 'Site' AND "preferences"."owner_id" IN (1)
down_retry_delay not reached for localhost:11211 (54.810 seconds left)
down_retry_delay not reached for localhost:11211 (54.809 seconds left)
  Site Load (0.5ms)  SELECT  "sites".* FROM "sites" WHERE "sites"."id" = $1 LIMIT 1  [["id", 1]]
  Preference Load (0.3ms)  SELECT "preferences".* FROM "preferences" WHERE "preferences"."owner_id" = $1 AND "preferences"."owner_type" = $2 AND "preferences"."group_id" IS NULL AND "preferences"."group_type" IS NULL  [["owner_id", 1], ["owner_type", "Site"]]
  List Load (0.5ms)  SELECT  "lists".* FROM "lists" WHERE "lists"."id" = $1 LIMIT 1  [["id", 300]]
  CheckList Exists (0.7ms)  SELECT  1 AS one FROM "lists" INNER JOIN "flags" ON "flags"."flaggable_id" = "lists"."id" AND "flags"."flaggable_type" = $1 WHERE "lists"."type" IN ('CheckList') AND "flags"."flag" = $2 AND "flags"."resolved" = $3 AND "lists"."id" = $4 LIMIT 1  [["flaggable_type", "List"], ["flag", "spam"], ["resolved", "f"], ["id", 300]]
  Role Load (0.5ms)  SELECT DISTINCT "roles".* FROM "roles" INNER JOIN "roles_users" ON "roles"."id" = "roles_users"."role_id" WHERE "roles_users"."user_id" = $1  [["user_id", 6]]
down_retry_delay not reached for localhost:11211 (54.796 seconds left)
down_retry_delay not reached for localhost:11211 (54.795 seconds left)
  Rendered text template (0.0ms)
Finished POST /lists/300/add_from_observations_now from ::1 for user: qwertyuiop 6
Completed 200 OK POST /lists/300/add_from_observations_now in 38ms (Views: 0.6ms | ActiveRecord: 6.8ms | Elasticsearch: 0.0ms)
```
both were previously broken as you described. I have an example checklist and a few taxa represented by obs locally

**Review by kueda — APPROVED** [review]

**Pull request merged**
